---

- name: Update apt cache.
  apt: 
    update_cache: yes 
    cache_valid_time: 86400
  changed_when: false

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx_package_name }}"
    state: latest
    default_release: "{{ nginx_default_release }}"

- name: Copy nginx configuration in place.
  template:
    src: nginx.debian.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
