## Ansible Role : Pip
- name: Ansible Pip package.
  hosts: ubuntu
  become: yes
  gather_facts: yes
  tags: ansible_os_family == 'Debian'
  remote_user: root
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: numpy
  roles:
    - pip

- name: Ansible Pip package.
  hosts: centos
  become: yes
  gather_facts: yes
  tags: ansible_os_family == 'RedHat'
  remote_user: root
  vars:
    pip_package: python-pip
    pip_install_packages:
      - name: numpy
  roles:
    - pip