---

- name: Ensure pip is installed
  yum:
    name: "{{ pip_package }}"
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    executable: pip
    state: latest

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable_redhat }}"
  with_items: "{{ pip_install_packages }}"
