---

- name: install python3-pip
  apt: 
    name:
      - python3
      - python3-minimal
      - python3-pip
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
