---
# tasks file for database

- name: Directory {{ docker_app_name }} check exists.
  stat:
    path: "{{ docker_path }}"
  register: dir_app_exists

- name: Pull repo if exists {{ docker_app_name }}.
  git:
    repo: '{{ docker_repo }}'
    dest: "{{ docker_path }}"
    clone: no
    update: yes
    accept_hostkey: yes
    version: master
    force: yes
  become: no
  register: pull_repo
  when: dir_app_exists.stat.exists

- name: Clone from repo {{ docker_app_name }}.
  git:
    repo: '{{ docker_repo }}'
    dest: "{{ docker_path }}"
    clone: yes
    update: no
    accept_hostkey: yes
    version: master
  become: no
  register: clone_repo
  when: dir_app_exists.stat.exists == False

- name: Logs permissons {{ docker_app_name }}.
  file:
    path: "{{ docker_logs }}"
    mode: 0777
    recurse: yes

- name: Create file .env {{ docker_app_name }}.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ env_source }}"

- name: Started docker compose {{ docker_app_name }}.
  docker_compose:
    project_src: "{{ docker_path }}"
    state: present
