---
# tasks file for docker

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: present
  notify: restart docker

- import_tasks: docker-1809-shim.yml
  when: ansible_service_mgr == 'systemd'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
