---

- name: Ensure old versions of Docker are not installed.
  yum:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: add Docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker Edge repo
  ini_file:
    dest: '/etc/yum.repos/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}.edge'
    option: enabled
    value: "{{ docker_yum_repo_enable_edge }}"

- name: Configure Docker Test repo
  ini_file:
    dest: '/etc/yum.repos/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}.test'
    option: enabled
    value: "{{ docker_yum_repo_enable_test }}"
