---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: idiots718/ubuntu18-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
