---
- name: Converge
  hosts: all
  vars:
    pip_package: python-pip
    pip_install_packages:
      - name: docker
      - name: docker-compose
    docker_app_name: docker-postgresql
    docker_path: /home/docker-postgresql
    docker_repo: git@gitlab.com:picasso-code/docker-postgresql.git
    docker_logs: /home/docker-postgresql/logs
    env_source:
      - { src: '.env.j2', dest: '/home/docker-postgresql' }
  pre_tasks:
    - name: Install Docker.
      include_role:
        name: docker
    - name: Install pip package.
      include_role:
        name: pip
  roles:
    - role: database
