---

- name: Download telegraf metrics agent.
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf-1.13.1-1.x86_64.rpm 
    dest: /opt
    mode: '0777'
    checksum: sha256:2a7abddeea7c200dc7d9d23a5eb97d5c0d8d45dad105555b6e250a048a78a70a

- name: Install telegraf metrics agent.
  command: yum localinstall telegraf-1.13.1-1.x86_64.rpm
  args:
    chdir: /opt

- name: Telegraf config metrics.
  template:
    src: "{{ item }}"
    dest: /etc/telegraf/telegraf.conf
  with_items: "{{ telegraf_agent }}"

- name: Root access /etc/telegraf.
  file:
    path: /etc/telegraf
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Permission docker to tekegraf
  command: usermod -aG docker telegraf

- name: Install python-pip
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pip
    - python-virtualenv

- name: Upgrade pip
  pip:
    name: pip
    executable: pip
    state: latest
